package dk.yrke.freezepom;

public interface Settings {
    String FREEZE_FILE_NAME = "pom.freeze";
    String AUTOGENERATED_FILE_MSG = "# This file is autogenerated do not change manually! To recreate run mvn freeze-pom:verify\n";
}
